### ISSUE TITLE
[Critical] Misleading activity status in notification

### ISSUE THREAD

**Issue by saalkom** [AU-COVIDSafe/mobile-android#13]
When Bluetooth is enabled but location services are not, the main COVIDSafe screen reports that it is not active yet the notification reports that it supposedly is. Given that I had to manually open the app to discover this and then press the red "Location: Off" text to be prompted to grant the new/updated location permissions and then manually enable location services, in the worst-case scenario millions of users may believe COVIDSafe is active in the background when it really isn't, thus putting the very effectiveness of the app into question after the most recent update.

![Screenshot_20200723-235241_COVIDSafe](https://user-images.githubusercontent.com/44572533/88296098-9edbe180-cd41-11ea-8d4d-c49a0d7f06bd.jpg)

![Screenshot_20200723-235854_COVIDSafe](https://user-images.githubusercontent.com/44572533/88296131-a7341c80-cd41-11ea-885c-ccb0d1454f75.jpg)

(Toggling Bluetooth does, however, automatically update the notification.)

Additionally, when location services are toggled on or off from QuickSettings, the main app screen does not automatically update to reflect this change, and the app must be relaunched either from the notification, home or apps screens, or the recents menu. This is not the case for changes in Bluetooth status, which are successfully automatically detected and reported on the main screen (and, for that matter, in the notification).

COVIDSafe 1.0.39
Android 9/Pie
SM-G955F / Samsung Galaxy S8+
Samsung OneUI 1.0

**Comment by a1291762** [comment]
I was going to make this exact comment on the other issue (where this was first raised).

The app should be warning me if it fails to scan, not just when I open the app.

**Comment by covidsafe-support** [comment]
Hi @saalkom, thanks for logging this issue - we've created a backlog task to look into this. We'll keep you updated in this issue when we have any progress to report or if we need further information.

**Comment by vteague** [comment]
@saalkom I actually think the*behaviour* of the app is correct/good, though I agree the UI/communication is awful.   

I did the following experiment:
- Turn on phone's location and bluetooth, install COVIDSafe, scan for messages (with my computer).  
This works, as expected.  My computer's scan can detect my phone's covidsafe msgs.

- Turn off phone's location, scan again.
As you observed, COVIDSafe's main screen complains that it is not active, but it does not raise a notification. 
Here's the thing: *it is actually still active*, and my computer's scan continues to detect is, just as before.

This is indeed, I believe, the correct way of dealing with [issue #6](https://github.com/AU-COVIDSafe/mobile-android/issues/6), which @jimmo logged a few weeks back.  See his explanation.  

Short summary: Android phones with Google's location services (i.e. global location setting) off will not be able to scan, but they will be able to respond.  Since COVIDSafe exchanges its TempIDs both ways between the peripheral and the central, this means that the inability to scan will completely prevent two Android phones that have location services off from recording each other's TempIDs.  However, having location services off shouldn't prevent an Android phone with location services from successful exchange with either iPhones or with Android phones that have location enabled.

They could have chosen to do what the EN API does, and insist that location must be enabled in order to run the app, but this means that users are deprived of the option to run in this mode and live without detection of other Android users who have turned off location.  I believe this is the right choice.

But there is no useful communication about this, and the way the app communicates that it is not working when it is, in fact, (mostly) working is profoundly unhelpful.

**Comment by covidsafe-team** [comment]
Hi @saalkom - thanks for your patience. This was fixed in release 1.0.48
