### ISSUE TITLE
Notification display bug

### ISSUE THREAD

**Issue by a1291762** [AU-COVIDSafe/mobile-android#8]
I have the notification set to silent so it is less prominent.

![Screenshot_20200706-100457~3](https://user-images.githubusercontent.com/327162/86601460-b21e4b80-bfe4-11ea-856a-8fcb449d5479.png)

However, the 1.0.33 version has display oddness. For example, after I took that screen shot, the notification hid and the silent notification bar went blank.

![Screenshot_20200706-100514~2](https://user-images.githubusercontent.com/327162/86601415-9e72e500-bfe4-11ea-8fbd-32faf2bcb74a.png)

This was fine with previous versions of covidsafe. It seems to also happen with a normal "alerting" notification too.
I have a xiaomi mi a2 lite running android 10.
I can get a logcat or anything else that might be helpful.

I am fairly certain that this issue is specific to covidsafe as other notifications appear to be working normally.

**Comment by a1291762** [comment]
I guess this (new in 1.0.33) is the cause?

    <?xml version="1.0" encoding="utf-8"?>
    <FrameLayout
        xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="0dp"
        android:layout_height="0dp">
    </FrameLayout> 

    val zeroHeightView = RemoteViews(context.packageName, R.layout.zero_height_view)
    val builder = NotificationCompat.Builder(context, channel)
        .setCustomContentView(zeroHeightView)

This looks like it is designed to "hide" the notification. Clearly it does not work in the normal case (screenshot 1), and it seems to cause this display issue when the notification is pushed down the screen (screenshot 2).

**Comment by ndavison** [comment]
Hi @a1291762, thanks for logging this issue - we've created a backlog task to look into this. We'll keep you updated in this issue when we have any progress to report or if we need further information.

**Comment by covidsafe-support** [comment]
Hi @a1291762, thanks for logging this issue - we've created a backlog task to look into this. We'll keep you updated in this issue when we have any progress to report or if we need further information.

**Comment by saalkom** [comment]
Possibly/probably an effect of the same underlying issue:

When active, COVIDSafe 1.0.33 breaks the display of other apps' notifications on the lockscreen in Samsung OneUI 1.0 under Android 9/Pie on my Galaxy S8+/SM-G955F. 

Normally, a maximum of three notifications appear on the lockscreen in their usual form and any extra notifications appear below them minimized so they appear only as icons. See the screenshot below for an example of five notifications on the lockscreen (including COVIDSafe) when Bluetooth is off:

![BT off](https://user-images.githubusercontent.com/44572533/86765878-1694e580-c08d-11ea-86ac-5b70f0d31e7d.jpg)

But now, when COVIDSafe 1.0.33 is active, of the 1 to 3 unminimized notifications, only some — if any at all — of the text of the bottom notification (or of the only notification, as the case may be) appears (which is different to merely being minimized/iconified, as the notification title (and, where applicable, the subtitle) does sometimes appear, just without any notification content, and notifications with media controls do appear but only partially), and none of the minimized/iconified notifications (if applicable) appear below the 3 unminimized notifications at all. Sometimes not even the icon of one of the notifications that theoretically aren't even minimized/iconified is displayed, and so that notification becomes totally invisible, but the location where that icon should be can still be tapped to be shown in expanded form in the notification drawer. The green "COVIDSafe is active" notification is no longer directly visible in any form on the lockscreen, which is a change I personally appreciate for the decreased clutter, but which I'd also put good money on being the culprit behind this mess. See the below screenshots for an example of what _should_ be four non-COVIDSafe notifications on the lockscreen (except the 'Do not disturb' notification is missing), as well as an example of what the lockscreen looks like when a media-player app is the only non-COVIDSafe notification not to have been dismissed (both screenshots were taken after Bluetooth was enabled):

![BT on, no DND notif](https://user-images.githubusercontent.com/44572533/86766593-19dca100-c08e-11ea-8c31-dde92eaff1ec.jpg)

Note that my email address is no longer displayed in the Gmail notification (I like that very specific side-effect actually, but I'm just using notifications from Gmail as an example — it happens with all apps). (NB: I choose to hide the content of notifications from 'Messages' on the lockscreen).

![BT on, all dismissed except media player controls](https://user-images.githubusercontent.com/44572533/86766609-1f39eb80-c08e-11ea-983f-e1b02f2ed35f.jpg)

When the device is still locked but the icon of a broken notification is tapped to expand its invisible(!) contents, the full notification drawer and notifications appear as normal and all is well in the world; the green "COVIDSafe is active" notification appears only as a small icon to the left of the 'Notification Settings' and 'Clear Notifications' buttons at the bottom of the drawer, which, again, if intentional behaviour, is personally appreciated, although sometimes it's only visible while pulling the notification drawer up to dismiss the drawer.

If it bears mentioning at all for any reason, when the device is unlocked the green "COVIDSafe is active" notification icon is visible in the statusbar (although, again, apparently absent from the notification drawer itself unless you pull the drawer back up) — I presume this, too, is mostly intentional, so, once more, it's appreciated and I hope this bug can be fixed without completely undoing these desirable changes.

**Comment by keegan-lillo** [comment]
I'm also seeing this on a Pixel 4.

**Comment by throrfj** [comment]
Just to say the same issue manifests slightly differently on my Pixel 3a.
When the screen is locked:
- the bottom notification from other apps is obscured, irrespective of how many there are (eg. if there is only one notification, it's obscured; or the second of two, etc)
- The small icon shows at the bottom of the drawer when it's being pulled up, as saalkom described
- no CovidSafe notification shows; 
When the screen is unlocked:
- the CovidSafe icon shows in the notification bar (when the phone is unlocked, like all my other notifications)
- But no actual notification shows when I pull down the drawer, when the phone is unlocked
- The small icon behaves the same as when locked

I've attached a couple of screenshots of the notifications being obscured as it displays differently to others who have posted.
![Screenshot_20200718-162933](https://user-images.githubusercontent.com/68459100/87847275-32647b00-c91a-11ea-9967-f914b8ee1c56.jpg)
![Screenshot_20200718-162916](https://user-images.githubusercontent.com/68459100/87847277-3395a800-c91a-11ea-9b28-148727cdd23b.jpg)

**Comment by a1291762** [comment]
Fixed in 1.0.39
